name: Build and Publish CV

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-cv-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      # - name: Compile LaTeX document
      #   uses: xu-cheng/latex-action@v2
      #   with:
      #     working_directory: fancy-cv
      #     root_file: |
      #       cv-en-industry-succinct.tex
      #       cv-es-industry-succinct.tex
      #     latexmk_use_xelatex: true

      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: cv-en-es.zip
      #     path: |
      #       ./fancy-cv/cv-en-industry-succinct.pdf
      #       ./fancy-cv/cv-es-industry-succinct.pdf

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   fallback: 1.4.0

      # - name: Get next version
      #   id: next
      #   uses: WyriHaximus/github-action-next-release-version@1.0.0
      #   with:
      #     version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:  ${{ steps.semvers.outputs.patch }}
          release_name: Release ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false

      - name: Attach 'cv-en-industry-succinct.pdf' to the Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fancy-cv/cv-en-industry-succinct.pdf
          asset_name: cv-en-industry-succinct.pdf
          asset_content_type: application/pdf

      - name: Attach 'cv-es-industry-succinct.pdf' to the Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fancy-cv/cv-es-industry-succinct.pdf
          asset_name: cv-es-industry-succinct.pdf
          asset_content_type: application/pdf

      # - name: Attach PDF to Release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./cv-en-es.zip
      #     asset_name: cv-en-es.zip
      #     asset_content_type: application/zip

          # asset_path: fancy-cv/main.pdf
          # asset_name: main.pdf
          # asset_content_type: application/pdf